- job_name: 'prometheus-federation'
  scheme: https
  scrape_interval: 15s
  honor_labels: true
  metrics_path: /federate
  basic_auth:
    username: <username>
    password: <password>
  params:
    'match[]':
      - '{job=~"^(kubelet|thanos-prometheus-operator-.*?|apiserver|kubelet|node-exporter)$"}'
  tls_config:
    insecure_skip_verify: true
  static_configs:
  - targets:
    - 'prometheus-0.<baseFQDN>'
    - 'prometheus-1.<baseFQDN>'

