{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gatekeeper-operator.serviceAccountName" . }}
  labels: {{- include "gatekeeper-operator.labels" . | nindent 4 }}
{{- end -}}
