{{ $root := .}}
{{- if .Values.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: {{ include "thanos-prometheus-operator.name" $root }}-prometheus
    role: default
  name: prometheus-operator.alerts
spec:
  groups:
  - name: prometheus-operator
    rules:
    - alert: PrometheusOperatorReconcileErrors
      annotations:
        message: {{` Errors while reconciling {{ $labels.controller }} in {{ $labels.namespace }} Namespace.`}}
      expr: 'rate(prometheus_operator_reconcile_errors_total{job="prometheus-operator",namespace="{{ .Release.Namespace }}"}[5m]) > 0.1'
      for: 10m
      labels:
        severity: warning
    - alert: PrometheusOperatorNodeLookupErrors
      annotations:
        message: {{` Errors while reconciling Prometheus in {{ $labels.namespace }} Namespace. `}}
      expr: 'rate(prometheus_operator_node_address_lookup_errors_total{job="prometheus-operator",namespace="{{ .Release.Namespace }}"}[5m]) > 0.1'
      for: 10m
      labels:
        severity: warning
{{- end }}
