{{- if .Values.operator.enabled }}
{{ $root := .}}
{{- range $path, $_ := .Files.Glob "files/rules/**.yaml" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: {{ include "thanos-prometheus-operator.name" $root }}-prometheus
    role: default
  name: {{ $path | trimSuffix ".yaml" | trimPrefix "files/rules/"}}
spec:
  groups:
{{ $.Files.Get $path | indent 2 }}
{{- end }}
{{ end -}}
