- name: kube-apiserver-error
  rules:
  - alert: ErrorBudgetBurn
    annotations:
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-errorbudgetburn
    expr: "(\n  status_class_5xx:apiserver_request_total:ratio_rate1h{job=\"apiserver\"\
      } > (14.4*0.010000)\n  and\n  status_class_5xx:apiserver_request_total:ratio_rate5m{job=\"\
      apiserver\"} > (14.4*0.010000)\n)\nor\n(\n  status_class_5xx:apiserver_request_total:ratio_rate6h{job=\"\
      apiserver\"} > (6*0.010000)\n  and\n  status_class_5xx:apiserver_request_total:ratio_rate30m{job=\"\
      apiserver\"} > (6*0.010000)\n)\n"
    labels:
      job: apiserver
      severity: critical
  - alert: ErrorBudgetBurn
    annotations:
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-errorbudgetburn
    expr: "(\n  status_class_5xx:apiserver_request_total:ratio_rate1d{job=\"apiserver\"\
      } > (3*0.010000)\n  and\n  status_class_5xx:apiserver_request_total:ratio_rate2h{job=\"\
      apiserver\"} > (3*0.010000)\n)\nor\n(\n  status_class_5xx:apiserver_request_total:ratio_rate3d{job=\"\
      apiserver\"} > (0.010000)\n  and\n  status_class_5xx:apiserver_request_total:ratio_rate6h{job=\"\
      apiserver\"} > (0.010000)\n)\n"
    labels:
      job: apiserver
      severity: warning
