- name: node.rules
  rules:
  - expr: 'sum(min(kube_pod_info) by (cluster, node))

      '
    record: ':kube_pod_info_node_count:'
  - expr: 'max(label_replace(kube_pod_info{job="kube-state-metrics"}, "pod", "$1",
      "pod", "(.*)")) by (node, namespace, pod)

      '
    record: 'node_namespace_pod:kube_pod_info:'
  - expr: "count by (cluster, node) (sum by (node, cpu) (\n  node_cpu_seconds_total{job=\"\
      node-exporter\"}\n* on (namespace, pod) group_left(node)\n  node_namespace_pod:kube_pod_info:\n\
      ))\n"
    record: node:node_num_cpu:sum
  - expr: "sum(\n  node_memory_MemAvailable_bytes{job=\"node-exporter\"} or\n  (\n\
      \    node_memory_Buffers_bytes{job=\"node-exporter\"} +\n    node_memory_Cached_bytes{job=\"\
      node-exporter\"} +\n    node_memory_MemFree_bytes{job=\"node-exporter\"} +\n\
      \    node_memory_Slab_bytes{job=\"node-exporter\"}\n  )\n) by (cluster)\n"
    record: :node_memory_MemAvailable_bytes:sum
