{
 "title": "Kubernetes / API server | Customer",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "s_customer",
    "label": "Schiff Customer",
    "query": "label_values(apiserver_request_total, schiff_customer)"
   },
   {
    "name": "s_cluster",
    "label": "Schiff Cluster",
    "query": "label_values(apiserver_request_total{schiff_customer=~\"^$s_customer$\"}, schiff_cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(apiserver_request_total{job=\"apiserver\", schiff_cluster=~\"^$s_cluster$\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up{job=\"apiserver\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", instance=~\"$instance\",code=~\"2..\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", instance=~\"$instance\",code=~\"3..\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", instance=~\"$instance\",code=~\"4..\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", instance=~\"$instance\",code=~\"5..\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\", instance=~\"$instance\", verb!=\"WATCH\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])) by (verb, le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"apiserver\", instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"apiserver\", instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"apiserver\", instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Entry Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_helper_cache_entry_total{job=\"apiserver\", instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Hit/Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_helper_cache_hit_total{job=\"apiserver\",instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} hit"
    },
    {
     "expr": "sum(rate(etcd_helper_cache_miss_total{job=\"apiserver\",instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "ETCD Cache Duration 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(etcd_request_cache_get_duration_seconds_bucket{job=\"apiserver\",instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} get"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(etcd_request_cache_add_duration_seconds_bucket{job=\"apiserver\",instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"apiserver\",instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"apiserver\",instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"apiserver\",instance=~\"$instance\", schiff_cluster=~\"^$s_cluster$\", schiff_customer=~\"^$s_customer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}