{{- if .Values.operator.exporters.coredns.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "thanos-prometheus-operator.fullname" . }}-coredns
  labels:
    app: {{ template "thanos-prometheus-operator.name" . }}-coredns
    jobLabel: coredns
{{ include "thanos-prometheus-operator.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.operator.exporters.coredns.service.port }}
      protocol: TCP
      targetPort: {{ .Values.operator.exporters.coredns.service.targetPort }}
  selector:
    {{- if .Values.operator.exporters.coredns.service.selector }}
{{ toYaml .Values.operator.exporters.coredns.service.selector | indent 4 }}
    {{- else}}
    k8s-app: kube-dns
    {{- end}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "thanos-prometheus-operator.fullname" . }}-coredns
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "thanos-prometheus-operator.name" . }}-coredns
{{ include "thanos-prometheus-operator.labels" . | indent 4 }}
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: {{ template "thanos-prometheus-operator.name" . }}-coredns
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    {{- if .Values.operator.exporters.coredns.serviceMonitor.interval}}
    interval: {{ .Values.operator.exporters.coredns.serviceMonitor.interval }}
    {{- end }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- if .Values.operator.exporters.coredns.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.operator.exporters.coredns.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.operator.exporters.coredns.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.operator.exporters.coredns.serviceMonitor.relabelings | indent 4 }}
{{- end }}
{{- end }}
