apiVersion: v1
kind: Service
metadata:
  labels: {{- include "gatekeeper.labels" . | nindent 4 }}
  name: {{ include "gatekeeper.fullname" . }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector: {{- include "gatekeeper.matchLabels" . | nindent 4 }}
