apiVersion: v1
kind: Service
metadata:
  labels: {{- include "gatekeeper.labels" . | nindent 4 }}
  name: {{ include "gatekeeper.fullname" . }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  {{- if .Values.prometheus.serviceMonitor.enabled }}
  - protocol: TCP
    port: 8888
    name: metrics
    targetPort: 8888
  {{- end }}
  selector: {{- include "gatekeeper.matchLabels" . | nindent 4 }}
