apiVersion: v2
name: thanos-prometheus-operator
description: The prometheus-operator flavoured with a grain of thanos.
appVersion: 0.37.0
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.2.2
keywords:
- prometheus
- alertmanager
- operator
- monitoring
home: https://github.com/coreos/prometheus-operator/
icon: https://bitnami.com/assets/stacks/prometheus-operator/img/prometheus-operator-stack-220x234.png
sources:
- https://github.com/coreos/prometheus-operator/
- https://github.com/thanos-io/thanos
dependencies:
  - name: thanos
    version: 0.1.7
    repository:  https://charts.bitnami.com/bitnami
    condition: query.enabled
    enabled: true
    alias: query
  - name: grafana
    version: 1.2.9
    repository: https://charts.bitnami.com/bitnami
    condition: grafana.enabled
  - name: prometheus-operator
    version: 0.13.1
    repository: https://charts.bitnami.com/bitnami
    condition: operator.enabled
    alias: operator

maintainers:
  - name: cellebyte
    url: https://github.com/Cellebyte
