federation:
  enabled: true
  ingress:
    baseFQDN: k8s.cluster.local # prometheus-1.<baseFQDN>, prometheus-2.<baseFQDN>


prometheus_operator:
  prometheus:
    externalLabels:
      federation_customer: "example-customer"
      federation_cluster: "example-cluster"
    listenLocal: false