apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tridenttransactions.trident.netapp.io
spec:
  group: trident.netapp.io
  names:
    categories:
    - trident-internal
    kind: TridentTransaction
    plural: tridenttransactions
    shortNames:
    - ttx
    - ttransaction
    singular: tridenttransaction
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
