apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tridentvolumes.trident.netapp.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    priority: 0
    type: date
  - JSONPath: .config.size
    description: The volume's size
    name: Size
    priority: 1
    type: string
  - JSONPath: .config.storageClass
    description: The volume's storage class
    name: Storage Class
    priority: 1
    type: string
  - JSONPath: .state
    description: The volume's state
    name: State
    priority: 1
    type: string
  - JSONPath: .config.protocol
    description: The volume's protocol
    name: Protocol
    priority: 1
    type: string
  - JSONPath: .backendUUID
    description: The volume's backend UUID
    name: Backend UUID
    priority: 1
    type: string
  - JSONPath: .pool
    description: The volume's pool
    name: Pool
    priority: 1
    type: string
  group: trident.netapp.io
  names:
    categories:
    - trident
    - trident-internal
    kind: TridentVolume
    plural: tridentvolumes
    shortNames:
    - tvol
    - tvolume
    singular: tridentvolume
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
