apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tridentsnapshots.trident.netapp.io
spec:
  additionalPrinterColumns:
  - JSONPath: .state
    description: The snapshot's state
    name: State
    priority: 1
    type: string
  group: trident.netapp.io
  names:
    categories:
    - trident
    - trident-internal
    kind: TridentSnapshot
    plural: tridentsnapshots
    shortNames:
    - tss
    - tsnap
    - tsnapshot
    singular: tridentsnapshot
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
