apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tridentstorageclasses.trident.netapp.io
spec:
  group: trident.netapp.io
  names:
    categories:
    - trident
    - trident-internal
    kind: TridentStorageClass
    plural: tridentstorageclasses
    shortNames:
    - tsc
    - tstorageclass
    singular: tridentstorageclass
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
