apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tridentnodes.trident.netapp.io
spec:
  group: trident.netapp.io
  names:
    categories:
    - trident
    - trident-internal
    kind: TridentNode
    plural: tridentnodes
    shortNames:
    - tnode
    singular: tridentnode
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
