apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tridentversions.trident.netapp.io
spec:
  additionalPrinterColumns:
  - JSONPath: .trident_version
    description: The Trident version
    name: Version
    priority: 0
    type: string
  group: trident.netapp.io
  names:
    categories:
    - trident
    - trident-internal
    kind: TridentVersion
    plural: tridentversions
    shortNames:
    - tver
    - tversion
    singular: tridentversion
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
