apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring-system
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring-system
      port: web
  baseImage: quay.io/prometheus/prometheus
  externalLabels:
    cluster: <cluster>
    customer: <customer>
  externalUrl: http://prometheus.k8s.cluster.local
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  retention: 20d
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.10.1
  version: v2.16.0
