apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-query
  name: thanos-query
  namespace: monitoring-system
spec:
  ports:
  - name: http
    port: 9090
    targetPort: http
  selector:
    app: thanos-query
  sessionAffinity: ClientIP
