## Default values for trident.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets
##
global:
#   imageRegistry: myRegistryName
  imagePullSecrets:
    - myRegistryKeySecretName

## String to partially override trident.fullname include (will maintain the release name)
##
# nameOverride:

## String to fully override trident.fullname template
##
# fullnameOverride:

rbac:
  # create specifies whether to install and use RBAC rules.
  create: true

trident:
  image:
    registry: docker.io
    repository: netapp/trident
    tag: 20.01.1
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  ## Trident container resource requests and limits
  ## This is currently unsupported
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## ref: https://projectcontour.io/guides/resource-limits/
  ##
  resources:
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: {}
      # cpu: 400m
      # memory: 250Mi
    requests: {}
      # cpu: 100m
      # memory: 25Mi

  livenessProbe:
    enabled: true
    failureThreshold: 2
    initialDelaySeconds: 120
    periodSeconds: 120
    timeoutSeconds: 90

  ## Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  ## Tolerations for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []

  ## Affinity for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}

  ## Pod annotations
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

prometheus:
  # Prometheus Operator service monitors
  serviceMonitor:
    # enable support for Prometheus Operator
    enabled: false
    # Job label for scrape target
    jobLabel: trident-csi
    # Scrape interval. If not set, the Prometheus default scrape interval is used.
    interval: ""
    metricRelabelings: []
    relabelings: []

## The CSI Containers which are deployed as SideCar containers to Trident.
## ref: https://netapp-trident.readthedocs.io/en/stable-v20.01/dag/kubernetes/concepts_and_definitions.html
csi:
  attacher:
    image:
      registry: quay.io
      repository: k8scsi/csi-attacher
      tag: v2.1.0
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent

  provisioner:
    image:
      registry: quay.io
      repository: k8scsi/csi-provisioner
      tag: v1.5.0
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent

  resizer:
    image:
      registry: quay.io
      respository: k8scsi/csi-resizer
      tag: v0.4.0
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent

  registrar:
    image:
      registry: quay.io
      repository: k8scsi/csi-node-driver-registrar
      tag: v1.2.0
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent

  snapshotter:
    image:
      registry: quay.io
      repository: k8scsi/csi-snapshotter
      tag: v2.0.1
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent

