---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "contour.fullname" . }}
  labels: {{- include "contour.labels" . | nindent 4 }}
    component: contour
spec:
  ports:
    - port: 8001
      name: xds
      protocol: TCP
      targetPort: 8001
  selector: {{- include "contour.matchLabels" . | nindent 4 }}
    component: contour
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "contour.fullname" . }}-envoy
  labels: {{- include "contour.labels" . | nindent 4 }}
    component: envoy
  annotations:
    # This annotation puts the AWS ELB into "TCP" mode so that it does not
    # do HTTP negotiation for HTTPS connections at the ELB edge.
    # The downside of this is the remote IP address of all connections will
    # appear to be the internal address of the ELB. See docs/proxy-proto.md
    # for information about enabling the PROXY protocol on the ELB to recover
    # the original remote IP address.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
  selector: {{- include "contour.matchLabels" . | nindent 4 }}
    component: envoy
  type: LoadBalancer