{{- if .Values.contour.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contour.contourServiceAccountName" . }}
  labels: {{- include "contour.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.certgen.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contour.contourCertGenServiceAccountName" . }}
  labels: {{- include "contour.labels" . | nindent 4 }}
{{- end }}