apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  
data:
  datasources.yaml: ew0KICAgICJhcGlWZXJzaW9uIjogMSwNCiAgICAiZGF0YXNvdXJjZXMiOiBbDQogICAgICAgIHsNCiAgICAgICAgICAgICJhY2Nlc3MiOiAicHJveHkiLA0KICAgICAgICAgICAgImVkaXRhYmxlIjogZmFsc2UsDQogICAgICAgICAgICAibmFtZSI6ICJwcm9tZXRoZXVzIiwNCiAgICAgICAgICAgICJvcmdJZCI6IDEsDQogICAgICAgICAgICAidHlwZSI6ICJwcm9tZXRoZXVzIiwNCiAgICAgICAgICAgICJ1cmwiOiAiaHR0cDovL3RoYW5vcy1xdWVyaWVyLm1vbml0b3Jpbmctc3lzdGVtLnN2Yzo5MDkwIiwNCiAgICAgICAgICAgICJ2ZXJzaW9uIjogMQ0KICAgICAgICB9DQogICAgXQ0KfQ0K
type: Opaque
