{{- if .Values.grafana.enabled -}}
apiVersion: v1
data:
  grafana.ini: {{ include "thanos-prometheus-operator.tplValue" ( dict "value" .Values.grafana.ini "context" $) | b64enc | quote }}
kind: Secret
metadata:
  name: grafana-config
type: Opaque
{{- end -}}
