apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: namespace-owner-provided
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    message: "All namespaces must have an `owner` label with the prefix of your @example.com email address (e.g. if your email address is peter.beispiel@example.com than you label `owner` should have value `peter.beispiel`)"
    labels:
      - key: owner
        allowedRegex: "^[a-zA-Z0-9_\\-\\.]+"
