apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBannedImageTags
metadata:
  name: ban-latest-tag
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    tags:
      - "latest"
{{- if .Values.allowedRegistries }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepositories
metadata:
 name: cluster-repo-is-harbor
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    repos:
    {{- range .Values.allowedRegistries }}
      - {{ . }}
    {{- end }}
{{- end }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: psp-privileged-container
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  {{- if .Values.excludedNamespaces }}
    excludedNamespaces:
    {{- range .Values.excludedNamespaces }}
      - {{ . }}
    {{- end }}
  {{- end }}
