apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "trident.fullname" . }}
  labels: {{- include "trident.labels" . | nindent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - "SYS_ADMIN"
  hostIPC: true
  hostNetwork: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
