apiVersion: v1
kind: Service
metadata:
  name: {{ include "trident.fullname" . }}-csi
  labels: {{- include "trident.labels" . | nindent 4 }}
spec:
  selector: {{- include "trident.matchLabels" . | nindent 4 }}
  ports:
  - name: https
    protocol: TCP
    port: 34571
    targetPort: 8443
  - name: metrics
    protocol: TCP
    port: 9220
    targetPort: 8001
