name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Helm Chart Testing Helm 3
      uses: HexF/chart-testing-action@v3.0.1
      with:
        command: helm lint charts/*
    - name: Helm Publish
      uses: J12934/helm-gh-pages-action@v1.1.0
      with:
        access-token:  ${{ secrets.ACCESS_TOKEN }}
