name: CI

on:
  push:
    branches:
      - release
      - dtcertmanager

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Helm 3
      uses: Azure/setup-helm@v1
      with:
        version: v3.1.0
    - name: Get all submodule charts
      run: git submodule update --init --recursive
    - name: Get all submodule tags
      run: git submodule foreach --recursive 'git fetch --tags'
    - name: Run bash script to update the chart version and the appVersion from version.txt
      run: bash external.sh
    - name: Lint Helm Charts
      run: helm lint charts/*
    - name: Add Bitnami repository
      run: helm repo add bitnami https://charts.bitnami.com/bitnami
    - name: Pull in all dependencies
      run: find 'charts/' -maxdepth 1 -mindepth 1 -exec helm dependency build {} \;
    - name: Package all Helm Charts
      run: find 'charts/' -maxdepth 1 -mindepth 1 -exec helm package {} \;
    - name: Checkout master
      run: git fetch --all && git checkout master && git status
    - name: Create new repoIndex
      run: helm repo index --url https://cellebyte.github.io/helm/ .
    - name: Add all files
      run: git add *.tgz index.yaml && git config --global user.email "actions@github.com" && git config --global user.name "CI GithubActions" && git commit -m "Updated Pages"
    - name: Push
      run: git push origin master
